# Generated by Django 5.2.12 on 2026-04-03 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department this shift is associated with.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shifts",
                to="scheduling.department",
            ),
        ),
    ]
