# Generated by Django 5.2.12 on 2026-04-04 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_alter_shift_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clock_in",
                    models.DateTimeField(help_text="When the employee clocked in."),
                ),
                (
                    "clock_out",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the employee clocked out (null if still clocked in).",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Manager adjustment notes or comments."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="The employee who clocked in/out.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        help_text="The shift this time entry is associated with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="scheduling.shift",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Entry",
                "verbose_name_plural": "Time Entries",
                "ordering": ["-clock_in"],
            },
        ),
    ]
